#TODO: fill secret values up

secretEnv:
  # o11y
  LANGFUSE_SECRET_KEY: "sk-lf-..."
  LANGFUSE_PUBLIC_KEY: "pk-lf-..."
  AWS_ACCESS_KEY_ID: "<redacted>"
  AWS_SECRET_ACCESS_KEY: "<redacted>"
  AWS_REGION: "auto"

  # Azure OpenAI
  OPENAI_API_KEY: xxxxx-xxxxx-xxxxx-xxxxx
  # AZURE_OPENAI_API_KEY: yyyyy-yyyyy-yyyyy-yyyyy
  # AZURE_CLIENT_SECRET:

  # Clova
  # CLOVA_API_KEY: nv-4xxxxxxxxxxx
